// 그래프 탐색 시뮬레이터가 쓰는 **지도 열두 장**. 맹목적 탐색과 정보 이용 탐색이 함께 쓴다.
//
// ## 왜 무작위로 만들지 않는가
//
// 아무렇게나 만든 그래프에서는 **최상 우선 탐색이 대개 A*와 같은 답을 낸다.** 그러면
// 「h만 보면 손해를 볼 수 있다」는 이 화면의 요점이 화면에 안 나온다. 그래서 지도는
// 조건을 걸어 골라 두고 **글자 그대로 얼려** 둔다.
//
// **여기 적힌 좌표를 손으로 고치지 마라.** 좌표가 곧 거리이고 거리가 곧 비용과 h(n)이라,
// 한 점만 옮겨도 아래 보증이 통째로 흔들린다. 지도를 다시 뽑으려면 `npm run gen:graph`,
// 뽑고 나면 `npm run check:graph`다. **무엇을 보증하는지는 그 검사가 안다** —
// 조건 목록을 여기 옮겨 적지 않는 이유다.
//
// ## 데이터 모양
//
// - `nodes`: `{id, x, y}`
// - `edges`: `{a, b, dir, extra}`
//   - `dir`: 방향을 켰을 때 어느 쪽으로 가는가. 'both' | 'a2b' | 'b2a'
//   - `extra`: 참이면 **이 간선이 사이클을 만든다.** 사이클을 끄면 이것들이 빠지고
//     남는 뼈대가 트리가 된다
export const GRAPH_PRESETS = [
    {
        id: 'map-1',
        name: '지도 1',
        start: 'B',
        goal: 'H',
        nodes: [
            {id: 'A', x: 116, y: 182},
            {id: 'B', x: 76, y: 308},
            {id: 'C', x: 221, y: 85},
            {id: 'D', x: 243, y: 277},
            {id: 'E', x: 409, y: 147},
            {id: 'F', x: 369, y: 367},
            {id: 'G', x: 493, y: 318},
            {id: 'H', x: 634, y: 121},
            {id: 'I', x: 624, y: 301},
        ],
        edges: [
            {a: 'G', b: 'I', dir: 'both'},
            {a: 'A', b: 'B', dir: 'a2b'},
            {a: 'F', b: 'G', dir: 'both'},
            {a: 'A', b: 'C', dir: 'b2a'},
            {a: 'D', b: 'F', dir: 'both'},
            {a: 'A', b: 'D', dir: 'a2b'},
            {a: 'H', b: 'I', dir: 'b2a'},
            {a: 'E', b: 'G', dir: 'both'},
            {a: 'B', b: 'D', dir: 'a2b', extra: true},
            {a: 'C', b: 'D', dir: 'b2a', extra: true},
            {a: 'C', b: 'E', dir: 'a2b', extra: true},
            {a: 'D', b: 'E', dir: 'both', extra: true},
        ],
    },
    {
        id: 'map-2',
        name: '지도 2',
        start: 'A',
        goal: 'H',
        nodes: [
            {id: 'A', x: 88, y: 260},
            {id: 'B', x: 167, y: 139},
            {id: 'C', x: 155, y: 375},
            {id: 'D', x: 279, y: 272},
            {id: 'E', x: 370, y: 159},
            {id: 'F', x: 493, y: 70},
            {id: 'G', x: 455, y: 349},
            {id: 'H', x: 634, y: 80},
            {id: 'I', x: 573, y: 198},
            {id: 'J', x: 647, y: 332},
        ],
        edges: [
            {a: 'H', b: 'I', dir: 'both'},
            {a: 'A', b: 'C', dir: 'both'},
            {a: 'F', b: 'H', dir: 'both'},
            {a: 'A', b: 'B', dir: 'both'},
            {a: 'D', b: 'E', dir: 'both'},
            {a: 'E', b: 'F', dir: 'both'},
            {a: 'I', b: 'J', dir: 'both'},
            {a: 'C', b: 'D', dir: 'both'},
            {a: 'G', b: 'I', dir: 'a2b'},
            {a: 'F', b: 'I', dir: 'both', extra: true},
            {a: 'B', b: 'D', dir: 'both', extra: true},
        ],
    },
    {
        id: 'map-3',
        name: '지도 3',
        start: 'A',
        goal: 'K',
        nodes: [
            {id: 'A', x: 81, y: 134},
            {id: 'B', x: 96, y: 274},
            {id: 'C', x: 246, y: 113},
            {id: 'D', x: 234, y: 255},
            {id: 'E', x: 385, y: 73},
            {id: 'F', x: 283, y: 385},
            {id: 'G', x: 428, y: 242},
            {id: 'H', x: 552, y: 71},
            {id: 'I', x: 478, y: 371},
            {id: 'J', x: 649, y: 163},
            {id: 'K', x: 649, y: 300},
        ],
        edges: [
            {a: 'H', b: 'J', dir: 'both'},
            {a: 'J', b: 'K', dir: 'both'},
            {a: 'G', b: 'I', dir: 'both'},
            {a: 'D', b: 'F', dir: 'both'},
            {a: 'B', b: 'D', dir: 'both'},
            {a: 'A', b: 'B', dir: 'b2a'},
            {a: 'C', b: 'D', dir: 'both'},
            {a: 'C', b: 'E', dir: 'a2b'},
            {a: 'E', b: 'H', dir: 'a2b'},
            {a: 'E', b: 'G', dir: 'both'},
            {a: 'A', b: 'C', dir: 'both', extra: true},
            {a: 'I', b: 'K', dir: 'a2b', extra: true},
        ],
    },
    {
        id: 'map-4',
        name: '지도 4',
        start: 'D',
        goal: 'J',
        nodes: [
            {id: 'A', x: 84, y: 70},
            {id: 'B', x: 111, y: 235},
            {id: 'C', x: 233, y: 125},
            {id: 'D', x: 90, y: 374},
            {id: 'E', x: 253, y: 355},
            {id: 'F', x: 403, y: 108},
            {id: 'G', x: 368, y: 239},
            {id: 'H', x: 385, y: 375},
            {id: 'I', x: 535, y: 173},
            {id: 'J', x: 623, y: 74},
            {id: 'K', x: 499, y: 308},
            {id: 'L', x: 642, y: 290},
        ],
        edges: [
            {a: 'H', b: 'K', dir: 'a2b'},
            {a: 'I', b: 'J', dir: 'both'},
            {a: 'E', b: 'H', dir: 'both'},
            {a: 'F', b: 'G', dir: 'both'},
            {a: 'G', b: 'H', dir: 'both'},
            {a: 'I', b: 'K', dir: 'both'},
            {a: 'B', b: 'D', dir: 'both'},
            {a: 'K', b: 'L', dir: 'both'},
            {a: 'A', b: 'C', dir: 'a2b'},
            {a: 'D', b: 'E', dir: 'both'},
            {a: 'B', b: 'C', dir: 'both'},
            {a: 'F', b: 'I', dir: 'both', extra: true},
            {a: 'G', b: 'K', dir: 'both', extra: true},
            {a: 'I', b: 'L', dir: 'b2a', extra: true},
            {a: 'E', b: 'G', dir: 'both', extra: true},
        ],
    },
    {
        id: 'map-5',
        name: '지도 5',
        start: 'B',
        goal: 'I',
        nodes: [
            {id: 'A', x: 150, y: 125},
            {id: 'B', x: 81, y: 371},
            {id: 'C', x: 177, y: 269},
            {id: 'D', x: 356, y: 144},
            {id: 'E', x: 292, y: 380},
            {id: 'F', x: 413, y: 267},
            {id: 'G', x: 551, y: 138},
            {id: 'H', x: 573, y: 338},
            {id: 'I', x: 649, y: 227},
        ],
        edges: [
            {a: 'G', b: 'I', dir: 'both'},
            {a: 'H', b: 'I', dir: 'both'},
            {a: 'D', b: 'F', dir: 'b2a'},
            {a: 'B', b: 'C', dir: 'both'},
            {a: 'A', b: 'C', dir: 'both'},
            {a: 'C', b: 'E', dir: 'both'},
            {a: 'E', b: 'F', dir: 'both'},
            {a: 'F', b: 'H', dir: 'both'},
            {a: 'F', b: 'G', dir: 'both', extra: true},
            {a: 'D', b: 'G', dir: 'a2b', extra: true},
        ],
    },
    {
        id: 'map-6',
        name: '지도 6',
        start: 'B',
        goal: 'H',
        nodes: [
            {id: 'A', x: 92, y: 101},
            {id: 'B', x: 107, y: 331},
            {id: 'C', x: 198, y: 183},
            {id: 'D', x: 336, y: 116},
            {id: 'E', x: 319, y: 288},
            {id: 'F', x: 509, y: 121},
            {id: 'G', x: 449, y: 242},
            {id: 'H', x: 645, y: 111},
            {id: 'I', x: 583, y: 238},
            {id: 'J', x: 521, y: 390},
        ],
        edges: [
            {a: 'A', b: 'C', dir: 'both'},
            {a: 'G', b: 'I', dir: 'both'},
            {a: 'F', b: 'G', dir: 'both'},
            {a: 'F', b: 'H', dir: 'both'},
            {a: 'E', b: 'G', dir: 'both'},
            {a: 'C', b: 'D', dir: 'both'},
            {a: 'C', b: 'E', dir: 'both'},
            {a: 'I', b: 'J', dir: 'b2a'},
            {a: 'B', b: 'C', dir: 'both'},
            {a: 'F', b: 'I', dir: 'b2a', extra: true},
            {a: 'H', b: 'I', dir: 'a2b', extra: true},
            {a: 'G', b: 'J', dir: 'both', extra: true},
            {a: 'D', b: 'G', dir: 'a2b', extra: true},
        ],
    },
    {
        id: 'map-7',
        name: '지도 7',
        start: 'B',
        goal: 'J',
        nodes: [
            {id: 'A', x: 137, y: 105},
            {id: 'B', x: 94, y: 387},
            {id: 'C', x: 185, y: 245},
            {id: 'D', x: 306, y: 119},
            {id: 'E', x: 273, y: 346},
            {id: 'F', x: 454, y: 72},
            {id: 'G', x: 417, y: 225},
            {id: 'H', x: 426, y: 372},
            {id: 'I', x: 539, y: 302},
            {id: 'J', x: 641, y: 142},
            {id: 'K', x: 643, y: 389},
        ],
        edges: [
            {a: 'H', b: 'I', dir: 'both'},
            {a: 'C', b: 'E', dir: 'both'},
            {a: 'I', b: 'K', dir: 'both'},
            {a: 'G', b: 'I', dir: 'both'},
            {a: 'A', b: 'C', dir: 'both'},
            {a: 'D', b: 'G', dir: 'both'},
            {a: 'E', b: 'H', dir: 'both'},
            {a: 'D', b: 'F', dir: 'both'},
            {a: 'B', b: 'C', dir: 'both'},
            {a: 'I', b: 'J', dir: 'both'},
            {a: 'G', b: 'H', dir: 'both', extra: true},
            {a: 'F', b: 'G', dir: 'a2b', extra: true},
            {a: 'A', b: 'D', dir: 'both', extra: true},
            {a: 'C', b: 'D', dir: 'a2b', extra: true},
        ],
    },
    {
        id: 'map-8',
        name: '지도 8',
        start: 'B',
        goal: 'J',
        nodes: [
            {id: 'A', x: 115, y: 151},
            {id: 'B', x: 73, y: 373},
            {id: 'C', x: 342, y: 81},
            {id: 'D', x: 274, y: 224},
            {id: 'E', x: 228, y: 365},
            {id: 'F', x: 486, y: 89},
            {id: 'G', x: 418, y: 265},
            {id: 'H', x: 361, y: 386},
            {id: 'I', x: 545, y: 227},
            {id: 'J', x: 634, y: 120},
            {id: 'K', x: 510, y: 361},
            {id: 'L', x: 641, y: 345},
        ],
        edges: [
            {a: 'K', b: 'L', dir: 'b2a'},
            {a: 'G', b: 'I', dir: 'both'},
            {a: 'G', b: 'K', dir: 'both'},
            {a: 'G', b: 'H', dir: 'both'},
            {a: 'E', b: 'H', dir: 'both'},
            {a: 'I', b: 'J', dir: 'both'},
            {a: 'C', b: 'F', dir: 'a2b'},
            {a: 'D', b: 'E', dir: 'both'},
            {a: 'F', b: 'I', dir: 'both'},
            {a: 'B', b: 'E', dir: 'both'},
            {a: 'A', b: 'D', dir: 'both'},
            {a: 'I', b: 'K', dir: 'b2a', extra: true},
            {a: 'D', b: 'G', dir: 'a2b', extra: true},
            {a: 'H', b: 'K', dir: 'b2a', extra: true},
        ],
    },
    {
        id: 'map-9',
        name: '지도 9',
        start: 'B',
        goal: 'H',
        nodes: [
            {id: 'A', x: 151, y: 147},
            {id: 'B', x: 141, y: 309},
            {id: 'C', x: 309, y: 113},
            {id: 'D', x: 271, y: 383},
            {id: 'E', x: 354, y: 259},
            {id: 'F', x: 451, y: 99},
            {id: 'G', x: 489, y: 262},
            {id: 'H', x: 593, y: 148},
            {id: 'I', x: 564, y: 373},
        ],
        edges: [
            {a: 'G', b: 'I', dir: 'both'},
            {a: 'E', b: 'G', dir: 'both'},
            {a: 'C', b: 'F', dir: 'both'},
            {a: 'D', b: 'E', dir: 'both'},
            {a: 'B', b: 'D', dir: 'both'},
            {a: 'F', b: 'H', dir: 'both'},
            {a: 'C', b: 'E', dir: 'a2b'},
            {a: 'A', b: 'C', dir: 'both'},
            {a: 'G', b: 'H', dir: 'a2b', extra: true},
            {a: 'A', b: 'B', dir: 'b2a', extra: true},
            {a: 'F', b: 'G', dir: 'a2b', extra: true},
            {a: 'E', b: 'F', dir: 'a2b', extra: true},
        ],
    },
    {
        id: 'map-10',
        name: '지도 10',
        start: 'A',
        goal: 'J',
        nodes: [
            {id: 'A', x: 104, y: 191},
            {id: 'B', x: 211, y: 108},
            {id: 'C', x: 125, y: 335},
            {id: 'D', x: 326, y: 181},
            {id: 'E', x: 432, y: 86},
            {id: 'F', x: 305, y: 361},
            {id: 'G', x: 579, y: 109},
            {id: 'H', x: 540, y: 305},
            {id: 'I', x: 648, y: 224},
            {id: 'J', x: 645, y: 387},
        ],
        edges: [
            {a: 'H', b: 'J', dir: 'both'},
            {a: 'G', b: 'I', dir: 'both'},
            {a: 'H', b: 'I', dir: 'both'},
            {a: 'A', b: 'B', dir: 'both'},
            {a: 'B', b: 'D', dir: 'both'},
            {a: 'D', b: 'E', dir: 'a2b'},
            {a: 'A', b: 'C', dir: 'both'},
            {a: 'E', b: 'G', dir: 'a2b'},
            {a: 'D', b: 'F', dir: 'both'},
            {a: 'I', b: 'J', dir: 'a2b', extra: true},
            {a: 'C', b: 'F', dir: 'b2a', extra: true},
            {a: 'G', b: 'H', dir: 'both', extra: true},
            {a: 'B', b: 'E', dir: 'a2b', extra: true},
        ],
    },
    {
        id: 'map-11',
        name: '지도 11',
        start: 'B',
        goal: 'J',
        nodes: [
            {id: 'A', x: 119, y: 80},
            {id: 'B', x: 89, y: 295},
            {id: 'C', x: 186, y: 194},
            {id: 'D', x: 211, y: 353},
            {id: 'E', x: 365, y: 138},
            {id: 'F', x: 304, y: 256},
            {id: 'G', x: 348, y: 385},
            {id: 'H', x: 573, y: 75},
            {id: 'I', x: 468, y: 262},
            {id: 'J', x: 633, y: 201},
            {id: 'K', x: 603, y: 330},
        ],
        edges: [
            {a: 'A', b: 'C', dir: 'both'},
            {a: 'J', b: 'K', dir: 'both'},
            {a: 'E', b: 'F', dir: 'b2a'},
            {a: 'C', b: 'F', dir: 'both'},
            {a: 'D', b: 'F', dir: 'both'},
            {a: 'B', b: 'D', dir: 'both'},
            {a: 'F', b: 'G', dir: 'both'},
            {a: 'H', b: 'J', dir: 'a2b'},
            {a: 'I', b: 'K', dir: 'both'},
            {a: 'E', b: 'I', dir: 'both'},
            {a: 'B', b: 'C', dir: 'a2b', extra: true},
            {a: 'D', b: 'G', dir: 'both', extra: true},
            {a: 'C', b: 'D', dir: 'b2a', extra: true},
        ],
    },
    {
        id: 'map-12',
        name: '지도 12',
        start: 'B',
        goal: 'J',
        nodes: [
            {id: 'A', x: 75, y: 70},
            {id: 'B', x: 72, y: 279},
            {id: 'C', x: 160, y: 177},
            {id: 'D', x: 268, y: 80},
            {id: 'E', x: 149, y: 390},
            {id: 'F', x: 253, y: 286},
            {id: 'G', x: 433, y: 88},
            {id: 'H', x: 363, y: 373},
            {id: 'I', x: 444, y: 242},
            {id: 'J', x: 630, y: 89},
            {id: 'K', x: 531, y: 388},
            {id: 'L', x: 608, y: 281},
        ],
        edges: [
            {a: 'K', b: 'L', dir: 'both'},
            {a: 'B', b: 'C', dir: 'a2b'},
            {a: 'B', b: 'E', dir: 'both'},
            {a: 'A', b: 'C', dir: 'both'},
            {a: 'F', b: 'H', dir: 'both'},
            {a: 'C', b: 'F', dir: 'both'},
            {a: 'C', b: 'D', dir: 'b2a'},
            {a: 'H', b: 'I', dir: 'a2b'},
            {a: 'G', b: 'I', dir: 'both'},
            {a: 'I', b: 'L', dir: 'both'},
            {a: 'J', b: 'L', dir: 'both'},
            {a: 'E', b: 'F', dir: 'both', extra: true},
            {a: 'D', b: 'G', dir: 'b2a', extra: true},
            {a: 'H', b: 'K', dir: 'both', extra: true},
        ],
    },
];

export default GRAPH_PRESETS;
