// 일차방정식 해 구하기 (Project 3-2-2) — C 언어 버전
const {makeDocument} = require('../make_sw_template');
const out = require('../../outpath');

makeDocument({
    s1: {
        programName: "일차방정식 해 구하기",
        purpose: [
            "ax ± b = c 형태의 일차방정식 문자열을 입력받아",
            "scanf로 토큰을 분리하고 strlen·atof로 계수·상수를 추출한 뒤 x의 값을 계산하여 출력한다.",
        ],
        targetUser: "일차방정식 풀이 과정을 프로그램으로 자동화하고 싶은 누구나",
        features: [
            "① ax ± b = c 형태의 방정식을 공백 포함 문자열로 한 줄 입력받는다.",
            "② scanf로 5개 토큰(ax / op / b_str / = / c_str)을 분리한다.",
            "③ strlen()과 '\\0' 삽입으로 계수 a를 추출하되, a=1 생략 시 1.0으로 처리한다.",
            "④ a=0 입력 시 미정의 동작을 방지하고 오류 메시지를 출력한다.",
            "⑤ 계산된 x가 정수면 %d로, 소수면 %.2f 형식으로 출력한다.",
        ],
        screenExample: [
            "(입력)  3x + 5 = 20",
            "(출력)  5",
        ],
    },

    s2: {
        programName: "일차방정식 해 구하기",
        inputDesign: [
            "ax ± b = c 형태의 방정식을 공백 포함 문자열로 한 줄 입력",
            "각 토큰 사이에 반드시 공백 1칸 필요 (예: '3x + 5 = 20')",
            "자료형: char[] → strlen()·atof()로 처리",
        ],
        inputExample: ["3x + 5 = 20"],
        outputDesign: [
            "x의 계산 결과를 한 줄 출력",
            "정수로 나누어떨어지면 %d, 소수가 나오면 %.2f 형식으로 출력",
        ],
        outputExample: ["5", "0.50  (소수인 경우)"],
        constraints: [
            "a=1 생략 케이스('x + 5 = 10'): ax 마지막 문자 제거 후 빈 문자열 → atof(\"\")=0.0이 되므로 삼항 연산자로 1.0 처리",
            "a=0 케이스('0x + 3 = 7'): C에서 0.0으로 나누면 미정의 동작(Undefined Behavior) 발생",
            "공백 없이 입력('3x+5=20'): scanf 토큰 분리가 달라져 프로그램 오작동",
            "처리 방법: a==0 조건 검사 필수, 삼항 연산자로 a=1 케이스 처리",
        ],
    },

    s3: {
        programName: "일차방정식 해 구하기",
        flowchart: [
            "① 시작",
            "② equation 입력",
            "③ scanf로 5개 토큰(ax, op, b_str, =, c_str) 분리",
            "④ ax[strlen(ax)-1] ← '\\0'  (마지막 'x' 제거)",
            "⑤ [ax[0] == '\\0' ?]",
            "     예  → a ← 1.0",
            "     아니오 → a ← atof(ax)",
            "⑥ op, b ← atof(b_str), c ← atof(c_str)",
            "⑦ [a == 0?]",
            "     예  → '오류: 일차방정식이 아닙니다.' 출력 후 끝",
            "     아니오 → 계속",
            "⑧ [op[0] == '+'?]",
            "     예  → x ← (c − b) / a",
            "     아니오 → x ← (c + b) / a",
            "⑨ [x == (int)x?]",
            "     예  → printf(\"%d\\n\", (int)x)",
            "     아니오 → printf(\"%.2f\\n\", x)",
            "⑩ 끝",
        ],
        pseudocode: [
            "scanf(\"%s %s %s %s %s\", ax, op, b_str, eq, c_str)",
            "ax[strlen(ax)-1] ← '\\0'",
            "",
            "if (ax[0] == '\\0')",
            "  a ← 1.0",
            "else",
            "  a ← atof(ax)",
            "",
            "b ← atof(b_str)",
            "c ← atof(c_str)",
            "",
            "if (a == 0)",
            "  출력('오류: 계수 a가 0이면 일차방정식이 아닙니다.')",
            "else",
            "  if (op[0] == '+')",
            "    x ← (c − b) / a",
            "  else",
            "    x ← (c + b) / a",
            "",
            "  if (x == (int)x)",
            "    printf(\"%d\\n\", (int)x)",
            "  else",
            "    printf(\"%.2f\\n\", x)",
        ],
    },

    s4: {
        programName: "일차방정식 해 구하기",
        code: [
            "#include <stdio.h>",
            "#include <string.h>",
            "#include <stdlib.h>",
            "",
            "int main() {",
            "    /* 1. 토큰 입력: \"ax op b = c\" 형식 */",
            "    char ax[20], op[5], b_str[20], eq[5], c_str[20];",
            "    scanf(\"%s %s %s %s %s\", ax, op, b_str, eq, c_str);",
            "",
            "    /* 2. 계수 a 추출: ax 마지막 문자('x') 제거 */",
            "    int len = strlen(ax);",
            "    ax[len - 1] = '\\0';",
            "    double a = (ax[0] == '\\0') ? 1.0 : atof(ax);",
            "",
            "    double b = atof(b_str);",
            "    double c = atof(c_str);",
            "",
            "    /* 3. a=0 검사 */",
            "    if (a == 0) {",
            "        printf(\"오류: 계수 a가 0이면 일차방정식이 아닙니다.\\n\");",
            "        return 0;",
            "    }",
            "",
            "    /* 4. 해 계산 */",
            "    double x;",
            "    if (op[0] == '+')",
            "        x = (c - b) / a;",
            "    else",
            "        x = (c + b) / a;",
            "",
            "    /* 5. 출력: 정수면 %d, 소수면 %.2f */",
            "    if (x == (int)x)",
            "        printf(\"%d\\n\", (int)x);",
            "    else",
            "        printf(\"%.2f\\n\", x);",
            "",
            "    return 0;",
            "}",
        ],
        explanation: [
            "1~3행: stdio.h(scanf/printf), string.h(strlen), stdlib.h(atof) 헤더 포함",
            "",
            "7~8행: 5개 토큰을 char 배열로 선언 후 scanf로 입력",
            "",
            "11~13행: ax 마지막 문자를 '\\0'으로 덮어 'x' 제거",
            "  빈 문자열(ax[0]=='\\0')이면 a=1.0, 아니면 atof()로 변환",
            "",
            "15~16행: b, c를 atof()로 실수형으로 변환",
            "",
            "19~22행: a=0 검사 후 오류 메시지 출력",
            "",
            "26~29행: op[0]이 '+'이면 x=(c-b)/a, '-'이면 x=(c+b)/a",
            "",
            "32~35행: x가 정수면 %d, 소수면 %.2f 형식으로 출력",
        ],
    },

    s5: {
        programName: "일차방정식 해 구하기",
        errors: [
            "ax[0]=='\\0' 처리를 빠뜨리면 a=atof(\"\")=0.0이 되어 ZeroDivision이 발생한다.",
            "(int)x 캐스팅으로 정수 여부를 판별할 때, x가 매우 큰 실수이면 오버플로우가 발생할 수 있다.",
        ],
        improvements: [
            "scanf 반환값(== 5)을 검사하면 토큰이 5개가 아닌 경우를 탐지할 수 있다.",
        ],
        testCases: [
            {input: "3x + 5 = 20", expected: "5", actual: "5", pass: "O"},
            {input: "3x - 5 = 10", expected: "5", actual: "5", pass: "O"},
            {input: "x + 5 = 10", expected: "5", actual: "5", pass: "O"},
            {input: "2x + 1 = 2", expected: "0.50", actual: "0.50", pass: "O"},
        ],
    },
}, out('실습', '일차방정식-해-구하기.c.docx'));
