// 일차방정식 해 구하기 (Project 3-2-2)
const {makeDocument} = require('./make_sw_template');
const out = require('../outpath');

makeDocument({
    s1: {
        programName: "일차방정식 해 구하기",
        purpose: [
            "ax ± b = c 형태의 일차방정식 문자열을 입력받아",
            "문자열 분리(split)와 슬라이싱으로 계수·상수를 추출한 뒤 x의 값을 계산하여 출력한다.",
        ],
        targetUser: "일차방정식 풀이 과정을 프로그램으로 자동화하고 싶은 누구나",
        features: [
            "① ax ± b = c 형태의 방정식을 공백 포함 문자열로 한 줄 입력받는다.",
            "② split()으로 5개 토큰(계수+미지수 / 연산자 / b / = / c)으로 분리한다.",
            "③ parts[0][:-1] 슬라이싱으로 계수 a를 추출하되, a=1 생략 시 1.0으로 처리한다.",
            "④ a=0 입력 시 ZeroDivisionError를 방지하고 오류 메시지를 출력한다.",
            "⑤ 계산된 x가 정수면 정수로, 소수면 소수점 둘째 자리까지 출력한다.",
        ],
        screenExample: [
            "(입력)  3x + 5 = 20",
            "(출력)  5",
        ],
    },

    s2: {
        programName: "일차방정식 해 구하기",
        inputDesign: [
            "ax ± b = c 형태의 방정식을 공백 포함 문자열로 한 줄 입력",
            "각 토큰 사이에 반드시 공백 1칸 필요 (예: '3x + 5 = 20')",
            "자료형: str → split() 후 각 토큰을 float으로 변환",
        ],
        inputExample: ["3x + 5 = 20"],
        outputDesign: [
            "x의 계산 결과를 한 줄 출력",
            "정수로 나누어떨어지면 정수, 소수가 나오면 소수점 둘째 자리까지 출력",
        ],
        outputExample: ["5", "0.5  (소수인 경우)"],
        constraints: [
            "a=1 생략 케이스('x + 5 = 10'): 'x'[:-1]이 빈 문자열 → float('') → ValueError 발생",
            "a=0 케이스('0x + 3 = 7'): 나눗셈에서 ZeroDivisionError 발생",
            "공백 없이 입력('3x+5=20'): split() 결과가 달라져 프로그램 오작동",
            "처리 방법: a=1 → 조건부 표현식(a_str if a_str else 1.0)으로 치환, a=0 → 오류 메시지 출력",
        ],
    },

    s3: {
        programName: "일차방정식 해 구하기",
        flowchart: [
            "① 시작",
            "② equation 입력",
            "③ parts ← equation.split()",
            "④ a_str ← parts[0][:-1]",
            "⑤ [a_str이 빈 문자열?]",
            "     예  → a ← 1.0",
            "     아니오 → a ← float(a_str)",
            "⑥ op ← parts[1],  b ← float(parts[2]),  c ← float(parts[4])",
            "⑦ [a == 0?]",
            "     예  → '오류: 일차방정식이 아닙니다.' 출력 후 끝",
            "     아니오 → 계속",
            "⑧ [op == '+'?]",
            "     예  → x ← (c − b) / a",
            "     아니오 → x ← (c + b) / a",
            "⑨ [x == int(x)?]",
            "     예  → print(int(x))",
            "     아니오 → print(round(x, 2))",
            "⑩ 끝",
        ],
        pseudocode: [
            "equation ← 입력()",
            "parts ← equation.split()",
            "a_str ← parts[0][:-1]",
            "",
            "if a_str이 비어 있으면:",
            "  a ← 1.0",
            "else:",
            "  a ← float(a_str)",
            "",
            "op ← parts[1]",
            "b  ← float(parts[2])",
            "c  ← float(parts[4])",
            "",
            "if a == 0:",
            "  출력('오류: 계수 a가 0이면 일차방정식이 아닙니다.')",
            "else:",
            "  if op == '+':",
            "    x ← (c − b) / a",
            "  else:",
            "    x ← (c + b) / a",
            "",
            "  if x == int(x):",
            "    출력(int(x))",
            "  else:",
            "    출력(round(x, 2))",
        ],
    },

    s4: {
        programName: "일차방정식 해 구하기",
        code: [
            "equation = input()",
            "parts = equation.split()",
            "",
            "# a = 1 처리: \"x\"[:-1] = \"\" → float(\"\") 오류 방지",
            "a_str = parts[0][:-1]               # \"3x\" → \"3\",  \"x\" → \"\"",
            "a = float(a_str) if a_str else 1.0  # 빈 문자열이면 계수는 1",
            "",
            "op = parts[1]",
            "b = float(parts[2])",
            "c = float(parts[4])  # parts[3]=\"=\"는 사용하지 않음",
            "",
            "# a = 0 처리: 0으로 나누면 ZeroDivisionError 발생",
            "if a == 0:",
            "    print(\"오류: 계수 a가 0이면 일차방정식이 아닙니다.\")",
            "else:",
            "    if op == '+':",
            "        x = (c - b) / a  # ax + b = c → x = (c - b) / a",
            "    else:",
            "        x = (c + b) / a  # ax - b = c → x = (c + b) / a",
            "",
            "    # 출력 형식: 정수면 정수, 소수면 소수점 2자리",
            "    if x == int(x):",
            "        print(int(x))",
            "    else:",
            "        print(round(x, 2))",
        ],
        explanation: [
            "1~2행: 방정식 문자열을 입력받아 공백 기준으로 분리",
            "  parts = ['3x', '+', '5', '=', '20']",
            "",
            "4~6행: 계수 a 추출 (a=1 예외 처리 포함)",
            "  parts[0][:-1]로 마지막 'x'를 제거",
            "  빈 문자열('')이면 조건부 표현식으로 1.0 대입",
            "",
            "8~10행: 연산자 op, 상수 b, 우변 c 추출",
            "  parts[3]='='는 사용하지 않으므로 parts[4]로 c를 가져옴",
            "",
            "13~19행: a=0 검사 후 x 계산",
            "  op='+' → x = (c−b) / a",
            "  op='-' → x = (c+b) / a",
            "",
            "21~24행: 출력 형식 결정",
            "  x가 정수면 int(x), 소수면 round(x, 2) 출력",
        ],
    },

    s5: {
        programName: "일차방정식 해 구하기",
        errors: [
            "f\"x의 값은 {x:.2f}입니다.\" 형식은 x=5일 때 '5.00'을 출력해,",
            "정수를 요구하는 온라인 채점(OJ) 시스템에서 오답 처리될 수 있다.",
        ],
        improvements: [
            "if x == int(x) 조건으로 정수 여부를 판별해 정수·소수 출력을 분기하면",
            "채점 시스템 통과율이 높아진다.",
        ],
        testCases: [
            {input: "3x + 5 = 20", expected: "5", actual: "5", pass: "O"},
            {input: "3x - 5 = 10", expected: "5", actual: "5", pass: "O"},
            {input: "x + 5 = 10", expected: "5", actual: "5", pass: "O"},
            {input: "2x + 1 = 2", expected: "0.5", actual: "0.5", pass: "O"},
        ],
    },
}, out('실습', '일차방정식-해-구하기.py.docx'));
