// 도서 대출 시스템 (Project 3-2-13) — Python 버전
const {makeDocument} = require('./make_sw_template');
const out = require('../outpath');

makeDocument({
    s1: {
        programName: "도서 대출 시스템",
        purpose: [
            "딕셔너리로 도서명과 상태를 관리하고, while True 루프로 사용자 명령(대출·반납·종료)을 반복 처리하는 도서 대출 시스템을 구현한다.",
        ],
        targetUser: "딕셔너리 탐색·수정과 while True/break 패턴을 학습하거나 실용적인 시스템 구현에 관심 있는 누구나",
        features: [
            "① 딕셔너리(Key: 도서명, Value: 상태)로 도서 정보를 초기화한다.",
            "② while True 루프로 명령을 반복 입력받고, 명령 0 입력 시 break로 종료한다.",
            "③ 명령 1(대출): 도서가 존재하고 '대출가능' 상태일 때만 '대출중'으로 변경한다.",
            "④ 명령 2(반납): 도서가 존재하고 '대출중' 상태일 때 '대출가능'으로 변경한다.",
        ],
        screenExample: [
            "(입력)  1 파이썬  → (출력) 파이썬 대출 완료",
            "(입력)  1 파이썬  → (출력) 이미 대출 중인 도서입니다.",
            "(입력)  1 수학    → (출력) 존재하지 않는 도서입니다.",
            "(입력)  2 파이썬  → (출력) 파이썬 반납 완료",
            "(입력)  0         → (종료)",
        ],
    },

    s2: {
        programName: "도서 대출 시스템",
        inputDesign: [
            "명령 형식: '번호 도서명' (공백 구분, 종료는 '0'만 입력)",
            "명령 1: 대출 요청 / 명령 2: 반납 요청 / 명령 0: 종료",
        ],
        inputExample: ["1 파이썬", "2 파이썬", "0"],
        outputDesign: [
            "대출 성공: '{도서명} 대출 완료'",
            "이미 대출 중: '이미 대출 중인 도서입니다.'",
            "반납 성공: '{도서명} 반납 완료'",
            "대출 가능 상태 반납 요청: '대출 중이 아닌 도서입니다.'",
            "없는 도서: '존재하지 않는 도서입니다.'",
        ],
        outputExample: ["파이썬 대출 완료", "파이썬 반납 완료"],
        constraints: [
            "도서 목록은 고정 초기값 (파이썬, C언어, 자바)",
            "명령 0 입력 시 도서명 없이 break로 즉시 종료",
            "title not in books를 가장 먼저 확인하여 KeyError 방지",
        ],
    },

    s3: {
        programName: "도서 대출 시스템",
        flowchart: [
            "① 시작",
            "② books ← {'파이썬':'대출가능', 'C언어':'대출가능', '자바':'대출가능'}",
            "③ while True:",
            "④   cmd ← input().split()",
            "⑤   if cmd[0] == '0': break",
            "⑥   op, title ← cmd[0], cmd[1]",
            "⑦   if title not in books: 출력('존재하지 않는 도서입니다.')",
            "⑧   elif op == '1':",
            "      if books[title] == '대출가능': books[title]='대출중', 출력('대출 완료')",
            "      else: 출력('이미 대출 중인 도서입니다.')",
            "⑨   elif op == '2':",
            "      if books[title] == '대출중': books[title]='대출가능', 출력('반납 완료')",
            "      else: 출력('대출 중이 아닌 도서입니다.')",
            "⑩ 끝",
        ],
        pseudocode: [
            "books ← {'파이썬':'대출가능', 'C언어':'대출가능', '자바':'대출가능'}",
            "",
            "while True:",
            "  cmd ← input().split()",
            "  if cmd[0] == '0': break",
            "",
            "  op, title ← cmd[0], cmd[1]",
            "",
            "  if title not in books:",
            "    출력('존재하지 않는 도서입니다.')",
            "  elif op == '1':",
            "    if books[title] == '대출가능':",
            "      books[title] = '대출중'",
            "      출력(title + ' 대출 완료')",
            "    else: 출력('이미 대출 중인 도서입니다.')",
            "  elif op == '2':",
            "    if books[title] == '대출중':",
            "      books[title] = '대출가능'",
            "      출력(title + ' 반납 완료')",
            "    else: 출력('대출 중이 아닌 도서입니다.')",
        ],
    },

    s4: {
        programName: "도서 대출 시스템",
        code: [
            "# 1. 도서 데이터 초기화 (Key: 도서명, Value: 상태)",
            "books = {\"파이썬\": \"대출가능\", \"C언어\": \"대출가능\", \"자바\": \"대출가능\"}",
            "",
            "# 2. 사용자 명령을 반복 처리 (0 입력 시 종료)",
            "while True:",
            "    cmd = input(\"명령 입력(1:대출 2:반납 0:종료): \").split()",
            "    if cmd[0] == '0': break  # 도서명 없이 0만 입력, 즉시 종료",
            "",
            "    op, title = cmd[0], cmd[1]",
            "",
            "    # 3. 도서 존재 여부를 가장 먼저 확인 (이후 분기 안전 보장)",
            "    if title not in books:",
            "        print(\"존재하지 않는 도서입니다.\")",
            "",
            "    # 4. 대출 처리",
            "    elif op == '1':",
            "        if books[title] == \"대출가능\":",
            "            books[title] = \"대출중\"",
            "            print(f\"{title} 대출 완료\")",
            "        else:",
            "            print(\"이미 대출 중인 도서입니다.\")",
            "",
            "    # 5. 반납 처리",
            "    elif op == '2':",
            "        if books[title] == \"대출중\":",
            "            books[title] = \"대출가능\"",
            "            print(f\"{title} 반납 완료\")",
            "        else:",
            "            print(\"대출 중이 아닌 도서입니다.\")",
        ],
        explanation: [
            "2행: 딕셔너리로 도서명(Key)과 상태(Value)를 초기화",
            "",
            "5~6행: while True로 무한 반복, '0' 입력 시 break로 즉시 탈출",
            "  cmd = input().split(): 입력을 공백으로 분리하여 리스트로 저장",
            "",
            "8행: op(명령번호)와 title(도서명) 분리",
            "  cmd[0]=='0' break로 먼저 처리되므로 cmd[1] 안전하게 접근 가능",
            "",
            "11~12행: title not in books → KeyError 방지를 위한 선제 확인",
            "",
            "15~20행: op=='1' 대출 처리 — 상태가 '대출가능'일 때만 '대출중'으로 변경",
            "22~27행: op=='2' 반납 처리 — 상태가 '대출중'일 때만 '대출가능'으로 변경",
        ],
    },

    s5: {
        programName: "도서 대출 시스템",
        errors: [
            "반납(op==2) 분기를 구현하지 않으면 반납 명령 입력 시 아무 처리도 되지 않는다. 반드시 elif op=='2' 분기 추가 필요.",
            "title not in books 검사를 생략하면 없는 도서명으로 접근 시 KeyError 발생. 존재 확인을 반드시 먼저 수행.",
        ],
        improvements: [
            "books.get(title)을 사용하면 키가 없을 때 None을 반환하여 KeyError 없이 안전하게 접근할 수 있다.",
            "도서 목록을 외부 파일(JSON)에서 읽도록 확장하면 더 실용적인 시스템이 된다.",
        ],
        testCases: [
            {input: "1 파이썬", expected: "파이썬 대출 완료", actual: "파이썬 대출 완료", pass: "O"},
            {input: "1 파이썬 (이미 대출)", expected: "이미 대출 중인 도서입니다.", actual: "이미 대출 중인 도서입니다.", pass: "O"},
            {input: "1 수학 (없는 도서)", expected: "존재하지 않는 도서입니다.", actual: "존재하지 않는 도서입니다.", pass: "O"},
            {input: "2 파이썬 (반납)", expected: "파이썬 반납 완료", actual: "파이썬 반납 완료", pass: "O"},
        ],
    },
}, out('실습', '도서-대출-시스템.py.docx'));
