// 철광석 제련 알고리즘 (Project 3-2-11) — C 언어 버전
const {makeDocument} = require('./make_sw_template');
const out = require('../outpath');

makeDocument({
    s1: {
        programName: "철광석 제련 알고리즘",
        purpose: [
            "5×5 광산 격자를 입력받아 3×3 제련기가 이동할 수 있는 모든 위치에서 합계를 계산하고, 그 중 최댓값을 출력한다.",
        ],
        targetUser: "2차원 배열 순회와 중첩 반복문을 학습하거나 슬라이딩 윈도우 기법에 관심 있는 누구나",
        features: [
            "① 2차원 int 배열 grid[5][5]에 scanf로 25개의 정수를 입력받는다.",
            "② 3×3 윈도우가 격자를 벗어나지 않는 시작점(i, j) 범위(0~2)를 탐색한다.",
            "③ 4중 for문으로 각 3×3 영역의 합계(current_sum)를 계산한다.",
            "④ 모든 윈도우 합계 중 최댓값(max_total)을 갱신하여 출력한다.",
        ],
        screenExample: [
            "(입력)  12 34 11 20 15",
            "        22 45 67 12  8",
            "        31 18  9 44 27",
            "         5 10 33 21 19",
            "        40  2 14 50  3",
            "(출력)  260",
        ],
    },

    s2: {
        programName: "철광석 제련 알고리즘",
        inputDesign: [
            "5줄에 걸쳐 각 줄마다 공백으로 구분된 5개의 정수가 입력됨",
            "자료형: int (scanf(\"%d\", &grid[i][j]))",
        ],
        inputExample: [
            "12 34 11 20 15",
            "22 45 67 12 8",
            "31 18 9 44 27",
            "5 10 33 21 19",
            "40 2 14 50 3",
        ],
        outputDesign: [
            "3×3 영역 합계의 최댓값 1개를 출력",
            "탐색 범위: 시작점 i, j ∈ {0,1,2} → 총 9가지 윈도우 위치",
        ],
        outputExample: ["260"],
        constraints: [
            "유효 시작점 수 = 격자 크기(5) − 윈도우 크기(3) + 1 = 3 → i, j < 3",
            "max_total = 0 초기화는 양수 보장 시 안전; 음수 포함 시 INT_MIN 사용",
        ],
    },

    s3: {
        programName: "철광석 제련 알고리즘",
        flowchart: [
            "① 시작",
            "② for (i=0; i<5; i++) for (j=0; j<5; j++) scanf grid[i][j]",
            "③ max_total ← 0",
            "④ for (i=0; i<3; i++):  (윈도우 시작 행)",
            "⑤   for (j=0; j<3; j++):  (윈도우 시작 열)",
            "⑥     current_sum ← 0",
            "⑦     for (r=i; r<i+3; r++):  (내부 행)",
            "⑧       for (c=j; c<j+3; c++):  (내부 열)",
            "⑨         current_sum += grid[r][c]",
            "⑩     if (current_sum > max_total) max_total ← current_sum",
            "⑪ printf(max_total)",
            "⑫ 끝",
        ],
        pseudocode: [
            "for (i=0; i<5; i++)",
            "  for (j=0; j<5; j++) scanf(\"%d\", &grid[i][j])",
            "",
            "max_total ← 0",
            "",
            "for (i=0; i<3; i++)",
            "  for (j=0; j<3; j++)",
            "    current_sum ← 0",
            "    for (r=i; r<i+3; r++)",
            "      for (c=j; c<j+3; c++)",
            "        current_sum += grid[r][c]",
            "    if (current_sum > max_total)",
            "      max_total ← current_sum",
            "",
            "printf(\"%d\\n\", max_total)",
        ],
    },

    s4: {
        programName: "철광석 제련 알고리즘",
        code: [
            "#include <stdio.h>",
            "",
            "int main() {",
            "    int grid[5][5];",
            "    int i, j, r, c;",
            "",
            "    /* 1. 5x5 격자 입력 */",
            "    for (i = 0; i < 5; i++)",
            "        for (j = 0; j < 5; j++)",
            "            scanf(\"%d\", &grid[i][j]);",
            "",
            "    /* 2. 최댓값 초기화 */",
            "    int max_total = 0;  /* 양수 보장 시 0, 범용은 INT_MIN */",
            "",
            "    /* 3. 3x3 윈도우 시작점 탐색 (0~2) */",
            "    for (i = 0; i < 3; i++) {",
            "        for (j = 0; j < 3; j++) {",
            "            int current_sum = 0;",
            "",
            "            /* 4. 3x3 내부 합계 계산 */",
            "            for (r = i; r < i + 3; r++)",
            "                for (c = j; c < j + 3; c++)",
            "                    current_sum += grid[r][c];",
            "",
            "            /* 5. 최댓값 갱신 */",
            "            if (current_sum > max_total)",
            "                max_total = current_sum;",
            "        }",
            "    }",
            "",
            "    printf(\"%d\\n\", max_total);",
            "    return 0;",
            "}",
        ],
        explanation: [
            "4~5행: 5×5 정수 배열 grid와 루프 변수 선언",
            "",
            "8~10행: 이중 for 루프로 25개의 정수를 grid[i][j]에 입력받음",
            "",
            "16~17행: 외부 이중 루프 — 3×3 윈도우의 시작점(i, j)을 0~2로 탐색",
            "  5-3+1=3이므로 i < 3, j < 3",
            "",
            "21~23행: 내부 이중 루프 — 시작점(i,j)에서 3×3 영역 합계 누적",
            "  r: i부터 i+2까지, c: j부터 j+2까지",
            "",
            "26~27행: 현재 윈도우 합계가 최댓값보다 크면 max_total 갱신",
        ],
    },

    s5: {
        programName: "철광석 제련 알고리즘",
        errors: [
            "외부 루프를 i < 5, j < 5로 설정하면 내부 루프에서 배열 범위를 벗어나 정의되지 않은 동작 발생. 반드시 i < 3, j < 3.",
            "max_total = 0으로 초기화하면 음수 격자에서 실제 최대 합이 음수여도 0이 출력된다. INT_MIN으로 초기화 권장.",
        ],
        improvements: [
            "루프 변수를 for 문 내부에서 선언(C99: int i)하면 변수 범위를 루프 안으로 제한할 수 있다.",
            "슬라이딩 윈도우 최적화: 이전 합계에서 이동한 열/행만 더하고 빼는 방식으로 연산 횟수를 줄일 수 있다.",
        ],
        testCases: [
            {input: "예시 데이터 (5×5)", expected: "260 (i=0,j=1 위치)", actual: "260", pass: "O"},
            {input: "모든 값 5 (5×5)", expected: "45 (9칸×5)", actual: "45", pass: "O"},
            {input: "최대값이 오른쪽 하단 (i=2,j=2)", expected: "57", actual: "57", pass: "O"},
            {input: "단일 최대값 위치 (i=1,j=1)", expected: "해당 3×3 합", actual: "정상 출력", pass: "O"},
        ],
    },
}, out('c', '3-2-11.docx'));
