// 도서 대출 시스템 (Project 3-2-13) — C 언어 버전
const {makeDocument} = require('./make_sw_template');
const out = require('../outpath');

makeDocument({
    s1: {
        programName: "도서 대출 시스템",
        purpose: [
            "병렬 배열(도서명 배열·상태 배열)로 도서를 관리하고, while 루프로 사용자 명령(대출·반납·종료)을 반복 처리하는 도서 대출 시스템을 구현한다.",
        ],
        targetUser: "C 언어 문자열 배열과 반복문을 학습하거나 딕셔너리 없이 Key-Value 구조를 구현하는 방법에 관심 있는 누구나",
        features: [
            "① 도서명 배열(names[][])과 상태 배열(status[])을 병렬로 선언하여 딕셔너리를 모방한다.",
            "② while(1) 루프로 명령을 반복 입력받고, 명령 0 입력 시 break로 종료한다.",
            "③ strcmp로 도서명을 탐색하고, 일치 시 status 배열에서 상태를 확인·변경한다.",
            "④ 명령 1(대출)·명령 2(반납)에 따라 상태를 0(대출가능)↔1(대출중)으로 전환한다.",
        ],
        screenExample: [
            "(입력)  1 파이썬  → (출력) 파이썬 대출 완료",
            "(입력)  1 파이썬  → (출력) 이미 대출 중인 도서입니다.",
            "(입력)  1 수학    → (출력) 존재하지 않는 도서입니다.",
            "(입력)  2 파이썬  → (출력) 파이썬 반납 완료",
            "(입력)  0         → (종료)",
        ],
    },

    s2: {
        programName: "도서 대출 시스템",
        inputDesign: [
            "명령 형식: '번호 도서명' (공백 구분, 종료는 '0'만 입력)",
            "명령 1: 대출 요청 / 명령 2: 반납 요청 / 명령 0: 종료",
            "자료형: 명령번호 int, 도서명 char[]",
        ],
        inputExample: ["1 파이썬", "2 파이썬", "0"],
        outputDesign: [
            "대출 성공: '{도서명} 대출 완료'",
            "이미 대출 중: '이미 대출 중인 도서입니다.'",
            "반납 성공: '{도서명} 반납 완료'",
            "대출 가능 상태 반납 요청: '대출 중이 아닌 도서입니다.'",
            "없는 도서: '존재하지 않는 도서입니다.'",
        ],
        outputExample: ["파이썬 대출 완료", "파이썬 반납 완료"],
        constraints: [
            "도서 목록은 고정 초기값 3권 (파이썬, C언어, 자바)",
            "상태: 0 = 대출가능, 1 = 대출중 (int 배열로 관리)",
            "도서 탐색은 strcmp를 사용한 선형 탐색 (string.h 필요)",
        ],
    },

    s3: {
        programName: "도서 대출 시스템",
        flowchart: [
            "① 시작",
            "② names[][] ← {'파이썬','C언어','자바'}, status[] ← {0,0,0}",
            "③ while(1):",
            "④   scanf op",
            "⑤   if (op == 0) break",
            "⑥   scanf title",
            "⑦   for (i=0; i<3; i++) if strcmp(names[i], title)==0: idx←i, break",
            "⑧   if (idx == -1): 출력('존재하지 않는 도서입니다.')",
            "⑨   else if (op == 1):",
            "      if status[idx]==0: status[idx]=1, 출력('대출 완료')",
            "      else: 출력('이미 대출 중인 도서입니다.')",
            "⑩   else if (op == 2):",
            "      if status[idx]==1: status[idx]=0, 출력('반납 완료')",
            "      else: 출력('대출 중이 아닌 도서입니다.')",
            "⑪ 끝",
        ],
        pseudocode: [
            "char names[3][20] = {\"파이썬\", \"C언어\", \"자바\"}",
            "int status[3] = {0, 0, 0}  /* 0=대출가능, 1=대출중 */",
            "",
            "while (1):",
            "  scanf op",
            "  if (op == 0) break",
            "  scanf title",
            "",
            "  idx ← -1",
            "  for i in 0..2:",
            "    if strcmp(names[i], title) == 0: idx ← i; break",
            "",
            "  if idx == -1: printf '존재하지 않는 도서입니다.'",
            "  else if op == 1:",
            "    if status[idx]==0: status[idx]=1; printf '대출 완료'",
            "    else: printf '이미 대출 중인 도서입니다.'",
            "  else if op == 2:",
            "    if status[idx]==1: status[idx]=0; printf '반납 완료'",
            "    else: printf '대출 중이 아닌 도서입니다.'",
        ],
    },

    s4: {
        programName: "도서 대출 시스템",
        code: [
            "#include <stdio.h>",
            "#include <string.h>  /* strcmp */",
            "",
            "int main() {",
            "    /* 1. 도서 데이터 초기화 (병렬 배열로 딕셔너리 모방) */",
            "    char names[3][20] = {\"파이썬\", \"C언어\", \"자바\"};",
            "    int status[3] = {0, 0, 0};  /* 0: 대출가능, 1: 대출중 */",
            "",
            "    int op;",
            "    char title[20];",
            "",
            "    /* 2. 명령 반복 처리 */",
            "    while (1) {",
            "        scanf(\"%d\", &op);",
            "        if (op == 0) break;  /* 0 입력 시 종료 */",
            "        scanf(\"%s\", title);",
            "",
            "        /* 3. 도서 탐색 (선형 탐색 + strcmp) */",
            "        int idx = -1;",
            "        for (int i = 0; i < 3; i++) {",
            "            if (strcmp(names[i], title) == 0) {",
            "                idx = i; break;",
            "            }",
            "        }",
            "",
            "        if (idx == -1) {",
            "            printf(\"존재하지 않는 도서입니다.\\n\");",
            "        } else if (op == 1) {  /* 대출 처리 */",
            "            if (status[idx] == 0) {",
            "                status[idx] = 1;",
            "                printf(\"%s 대출 완료\\n\", title);",
            "            } else {",
            "                printf(\"이미 대출 중인 도서입니다.\\n\");",
            "            }",
            "        } else if (op == 2) {  /* 반납 처리 */",
            "            if (status[idx] == 1) {",
            "                status[idx] = 0;",
            "                printf(\"%s 반납 완료\\n\", title);",
            "            } else {",
            "                printf(\"대출 중이 아닌 도서입니다.\\n\");",
            "            }",
            "        }",
            "    }",
            "    return 0;",
            "}",
        ],
        explanation: [
            "1~2행: stdio.h (입출력), string.h (strcmp) 헤더 포함",
            "",
            "6행: names[3][20] — 3권의 도서명을 2차원 char 배열로 저장",
            "7행: status[3] — 각 도서의 상태를 int로 저장 (0=대출가능, 1=대출중)",
            "",
            "13~14행: scanf로 명령 번호 입력받고, 0이면 break로 종료",
            "15행: 명령 1·2에서만 도서명 추가 입력받음",
            "",
            "18~22행: strcmp로 names 배열을 순회하며 일치하는 도서 인덱스 탐색",
            "  idx == -1이면 목록에 없는 도서",
            "",
            "24~38행: idx로 status 배열에 접근하여 상태 확인·변경 후 메시지 출력",
        ],
    },

    s5: {
        programName: "도서 대출 시스템",
        errors: [
            "반납(op==2) 분기를 누락하면 반납 명령 입력 시 아무 처리도 되지 않는다. 반드시 else if (op==2) 분기 추가 필요.",
            "strcmp 없이 names[i] == title로 비교하면 포인터 비교가 되어 항상 false. 반드시 strcmp(names[i], title) == 0 사용.",
        ],
        improvements: [
            "도서 수를 상수(#define BOOK_COUNT 3)로 정의하면 추가 도서 시 루프 범위를 한 곳에서만 수정하면 된다.",
            "names 배열을 동적 입력으로 바꾸면 프로그램 수정 없이 도서 목록을 변경할 수 있다.",
        ],
        testCases: [
            {input: "1 파이썬", expected: "파이썬 대출 완료", actual: "파이썬 대출 완료", pass: "O"},
            {input: "1 파이썬 (이미 대출)", expected: "이미 대출 중인 도서입니다.", actual: "이미 대출 중인 도서입니다.", pass: "O"},
            {input: "1 수학 (없는 도서)", expected: "존재하지 않는 도서입니다.", actual: "존재하지 않는 도서입니다.", pass: "O"},
            {input: "2 파이썬 (반납)", expected: "파이썬 반납 완료", actual: "파이썬 반납 완료", pass: "O"},
        ],
    },
}, out('c', '3-2-13.docx'));
