// 데이터 신뢰성 검사: 바코드 검증 (Project 3-2-5)
const {makeDocument} = require('./make_sw_template');
const out = require('../outpath');

makeDocument({
    s1: {
        programName: "데이터 신뢰성 검사: 바코드 검증",
        purpose: [
            "8자리 바코드를 입력받아 체크섬 알고리즘으로 마지막 자리(체크 숫자)의 유효성을 검증하고, 일치하면 'Valid', 불일치하면 'Invalid'를 출력한다.",
        ],
        targetUser: "바코드 체크섬 알고리즘을 학습하거나 데이터 무결성 검증에 관심 있는 누구나",
        features: [
            "① 8자리 숫자를 공백 없이 문자열로 입력받는다.",
            "② 앞 7자리에서 홀수 번째 자리 합(S1)과 짝수 번째 자리 합(S2)을 구한다.",
            "③ total = S1 + S2×3, result = (10 − total%10) % 10으로 체크 숫자를 도출한다.",
            "④ result와 8번째 자리 숫자가 일치하면 Valid, 아니면 Invalid를 출력한다.",
        ],
        screenExample: [
            "(입력)  88012340",
            "(출력)  Valid",
        ],
    },

    s2: {
        programName: "데이터 신뢰성 검사: 바코드 검증",
        inputDesign: [
            "8자리 숫자를 공백 없이 문자열로 한 줄 입력",
            "자료형: str (각 자리수는 int()로 개별 변환)",
        ],
        inputExample: ["88012340"],
        outputDesign: [
            "체크 숫자가 올바르면 'Valid', 틀리면 'Invalid' 출력",
        ],
        outputExample: ["Valid", "Invalid  (체크 숫자가 틀린 경우)"],
        constraints: [
            "8자리 미만 입력 시 barcode[7]에서 IndexError: string index out of range 발생",
            "숫자가 아닌 문자 입력 시 int() 변환에서 ValueError 발생",
            "처리 방법: if len(barcode) != 8 조건으로 입력 길이 유효성 검사 추가 권장",
        ],
    },

    s3: {
        programName: "데이터 신뢰성 검사: 바코드 검증",
        flowchart: [
            "① 시작",
            "② barcode 입력",
            "③ data ← barcode[:7],  check_digit ← int(barcode[7])",
            "④ s1 ← 0,  s2 ← 0",
            "⑤ for i in range(7):",
            "     num ← int(data[i])",
            "     [(i+1) % 2 == 1?]",
            "       예  → s1 ← s1 + num",
            "       아니오 → s2 ← s2 + num",
            "⑥ total_sum ← s1 + s2 × 3",
            "⑦ result ← (10 − total_sum % 10) % 10",
            "⑧ [result == check_digit?]",
            "     예  → 'Valid' 출력",
            "     아니오 → 'Invalid' 출력",
            "⑨ 끝",
        ],
        pseudocode: [
            "barcode ← 입력()",
            "data ← barcode[:7]",
            "check_digit ← int(barcode[7])",
            "s1 ← 0,  s2 ← 0",
            "",
            "for i in range(7):",
            "  num ← int(data[i])",
            "  if (i + 1) % 2 == 1:",
            "    s1 ← s1 + num",
            "  else:",
            "    s2 ← s2 + num",
            "",
            "total_sum ← s1 + s2 × 3",
            "result ← (10 − total_sum % 10) % 10",
            "",
            "if result == check_digit:",
            "  출력('Valid')",
            "else:",
            "  출력('Invalid')",
        ],
    },

    s4: {
        programName: "데이터 신뢰성 검사: 바코드 검증",
        code: [
            "# 1. 바코드 입력 (문자열 8자리)",
            "barcode = input()",
            "",
            "# 2. 앞 7자리(data)와 마지막 체크 숫자 분리",
            "#    barcode[7] → 인덱스 7 = 8번째 자리 = 체크 숫자",
            "data = barcode[:7]",
            "check_digit = int(barcode[7])",
            "",
            "# 3. 홀수/짝수 자리 합계 계산",
            "s1 = 0  # 홀수 번째(1·3·5·7번) 자리 합",
            "s2 = 0  # 짝수 번째(2·4·6번) 자리 합",
            "",
            "for i in range(7):  # i = 0, 1, 2, 3, 4, 5, 6",
            "    num = int(data[i])",
            "    if (i + 1) % 2 == 1:  # (i+1)이 홀수 → 홀수 번째 자리",
            "        s1 += num",
            "    else:                 # (i+1)이 짝수 → 짝수 번째 자리",
            "        s2 += num",
            "",
            "# 4. 체크 숫자 도출",
            "total_sum = s1 + (s2 * 3)       # 홀수합 + 짝수합×3",
            "remainder = total_sum % 10",
            "result = (10 - remainder) % 10  # remainder=0이면 10→0으로 처리",
            "",
            "# 5. 결과 출력",
            "if result == check_digit:",
            "    print('Valid')",
            "else:",
            "    print('Invalid')",
        ],
        explanation: [
            "1행: 바코드를 문자열로 입력받음",
            "",
            "5~6행: 슬라이싱으로 앞 7자리와 체크 숫자 분리",
            "  barcode[:7] → 인덱스 0~6 (7개)",
            "  barcode[7]  → 인덱스 7 = 8번째 자리",
            "",
            "12~17행: 반복문으로 홀수/짝수 자리 분류",
            "  (i+1)%2==1 → 홀수 번째 자리 → s1에 합산",
            "  (i+1)%2==0 → 짝수 번째 자리 → s2에 합산",
            "",
            "20~22행: 체크 숫자 계산",
            "  total_sum = s1 + s2×3",
            "  (10−remainder)%10 으로 remainder=0일 때 10→0 처리",
            "",
            "25~28행: result와 check_digit 비교 후 Valid/Invalid 출력",
        ],
    },

    s5: {
        programName: "데이터 신뢰성 검사: 바코드 검증",
        errors: [
            "int() 변환 없이 data[i]를 그대로 더하면 문자열 연결이 발생한다.",
            "(10 − remainder)만 쓰면 remainder=0일 때 결과가 10이 되어 체크 숫자(0~9)와 일치하지 않는다.",
        ],
        improvements: [
            "len(barcode) != 8 조건으로 입력 길이를 검사하면 IndexError를 방어할 수 있다.",
        ],
        testCases: [
            {input: "88012340", expected: "Valid", actual: "Valid", pass: "O"},
            {input: "88012345", expected: "Invalid", actual: "Invalid", pass: "O"},
            {input: "00000000", expected: "Valid", actual: "Valid", pass: "O"},
            {input: "12345678", expected: "Valid", actual: "Valid", pass: "O"},
        ],
    },
}, out('실습', '바코드-검증.py.docx'));
