// 비만도 측정 프로그램 (Project 3-2-1) — C 언어 버전
const {makeDocument} = require('./make_sw_template');

makeDocument({
    s1: {
        programName: "비만도 측정 프로그램",
        purpose: [
            "키와 몸무게를 입력받아 표준 몸무게를 기준으로 비만도(%)를 계산하고,",
            "정상·과체중·비만 여부를 판정하여 출력한다.",
        ],
        targetUser: "자신의 비만도를 간단히 확인하고 싶은 누구나",
        features: [
            "① 키(cm)와 몸무게(kg)를 공백으로 구분하여 한 줄로 입력받는다.",
            "② 키 구간(150 미만 / 150~160 미만 / 160 이상)에 따라 표준 몸무게(sw)를 계산한다.",
            "③ 비만도(%) = (실제 몸무게 − 표준 몸무게) × 100 ÷ 표준 몸무게 수식을 적용한다.",
            "④ 비만도에 따라 '정상', '과체중', '비만' 중 하나를 출력한다.",
        ],
        screenExample: [
            "(입력)  170 80",
            "(출력)  비만",
        ],
    },

    s2: {
        programName: "비만도 측정 프로그램",
        inputDesign: [
            "키(cm)와 몸무게(kg)를 공백으로 구분하여 한 줄로 입력",
            "자료형: double (실수형)",
        ],
        inputExample: ["170 80"],
        outputDesign: [
            "비만도 판정 결과를 문자열로 한 줄 출력",
            "('정상', '과체중', '비만' 중 하나)",
        ],
        outputExample: ["비만"],
        constraints: [
            "숫자가 아닌 문자 입력 시 scanf 반환값이 2 미만이 되어 변수에 쓰레기값이 남음",
            "음수 키·몸무게 입력 시 표준 몸무게 계산 결과가 비정상이 될 수 있음",
            "처리 방법: scanf 반환값(== 2) 검사 또는 입력 후 if 조건으로 범위 검증 권장",
        ],
    },

    s3: {
        programName: "비만도 측정 프로그램",
        flowchart: [
            "① 시작",
            "② height, weight 입력",
            "③ [키 구간 판정]",
            "   height < 150",
            "     → sw = height − 100",
            "   150 ≤ height < 160",
            "     → sw = (height−150)/2.0 + 50",
            "   height ≥ 160",
            "     → sw = (height−100) × 0.9",
            "④ obesity = (weight−sw)×100/sw",
            "⑤ [비만도 판정]",
            "   obesity ≤ 10   →  '정상' 출력",
            "   obesity ≤ 20   →  '과체중' 출력",
            "   그 외            →  '비만' 출력",
            "⑥ 끝",
        ],
        pseudocode: [
            "scanf(\"%lf %lf\", &height, &weight)",
            "",
            "if (height < 150)",
            "  sw = height − 100",
            "else if (height < 160)",
            "  sw = (height−150)/2.0 + 50",
            "else",
            "  sw = (height−100) × 0.9",
            "",
            "obesity = (weight−sw)×100/sw",
            "",
            "if (obesity <= 10)",
            "  printf(\"정상\\n\")",
            "else if (obesity <= 20)",
            "  printf(\"과체중\\n\")",
            "else",
            "  printf(\"비만\\n\")",
        ],
    },

    s4: {
        programName: "비만도 측정 프로그램",
        code: [
            "#include <stdio.h>",
            "",
            "int main() {",
            "    /* 1. 입력 받기 (실수형으로 변환) */",
            "    double height, weight;",
            "    scanf(\"%lf %lf\", &height, &weight);",
            "",
            "    /* 2. 표준 몸무게(sw) 계산 */",
            "    double sw;",
            "    if (height < 150)",
            "        sw = height - 100;",
            "    else if (height < 160)",
            "        sw = (height - 150) / 2.0 + 50;",
            "    else",
            "        sw = (height - 100) * 0.9;",
            "",
            "    /* 3. 비만도 계산 */",
            "    double obesity = (weight - sw) * 100 / sw;",
            "",
            "    /* 4. 결과 판정 및 출력 */",
            "    if (obesity <= 10)",
            "        printf(\"정상\\n\");",
            "    else if (obesity <= 20)",
            "        printf(\"과체중\\n\");",
            "    else",
            "        printf(\"비만\\n\");",
            "",
            "    return 0;",
            "}",
        ],
        explanation: [
            "1행: #include <stdio.h> — scanf/printf 사용을 위한 헤더 포함",
            "3행: int main() — C 프로그램의 진입점",
            "",
            "5~6행: double 타입으로 키·몸무게 선언 후 scanf로 입력",
            "  %lf 서식으로 실수(double) 입력",
            "",
            "10~15행: 키 구간별 표준 몸무게 공식",
            "  H < 150    →  sw = H − 100",
            "  150~160    →  sw = (H−150)/2.0+50  (2.0 필수!)",
            "  H ≥ 160    →  sw = (H−100)×0.9",
            "",
            "18행: 비만도(%) 계산",
            "  (실제 − 표준) × 100 ÷ 표준",
            "",
            "21~26행: 비만도 범위로 판정·출력",
            "  ≤ 10  →  '정상'",
            "  ≤ 20  →  '과체중'",
            "  초과  →  '비만'",
        ],
    },

    s5: {
        programName: "비만도 측정 프로그램",
        errors: [
            "obesity <= 10 조건으로 인해 음수 비만도(저체중)도 '정상'으로 출력될 수 있다.",
            "(height-150)/2로 쓰면 정수 나눗셈이 되어 소수점이 잘린다. 반드시 /2.0을 사용해야 한다.",
        ],
        improvements: [
            "저체중 분기 추가: if (obesity < 0) printf(\"저체중\\n\");를 최상단에 삽입하면 4가지 판정이 가능하다.",
        ],
        testCases: [
            {input: "170 80", expected: "비만", actual: "비만", pass: "O"},
            {input: "170 69", expected: "정상", actual: "정상", pass: "O"},
            {input: "170 70", expected: "과체중", actual: "과체중", pass: "O"},
            {input: "140 40", expected: "정상", actual: "정상", pass: "O"},
        ],
    },
}, "../c/3-2-1.docx");
