// 교집합과 합집합 계산기 (Project 3-2-14) — C 언어 버전
const {makeDocument} = require('./make_sw_template');

makeDocument({
    s1: {
        programName: "교집합과 합집합 계산기",
        purpose: [
            "두 집합의 원소를 입력받아 교집합(공통 원소)과 합집합(전체 원소)을 오름차순으로 정렬하여 출력한다. 교집합이 공집합이면 0을 출력한다.",
        ],
        targetUser: "C 언어 배열 탐색과 버블 정렬을 학습하거나 집합 연산을 배열로 직접 구현하는 방법에 관심 있는 누구나",
        features: [
            "① 두 줄로 각각 공백 구분 정수를 입력받아 배열에 저장한다.",
            "② 교집합: 배열 A의 각 원소가 배열 B에도 존재하는지 선형 탐색으로 확인한다.",
            "③ 합집합: 배열 A의 모든 원소와 배열 B의 원소 중 A에 없는 것을 합산한다.",
            "④ 버블 정렬로 결과를 오름차순 정렬하고 출력한다.",
        ],
        screenExample: [
            "(입력)  1 2 3 4",
            "        3 4 5 6",
            "(출력)  3 4       (교집합)",
            "        1 2 3 4 5 6  (합집합)",
        ],
    },

    s2: {
        programName: "교집합과 합집합 계산기",
        inputDesign: [
            "1행: 집합 A 원소 수 n, 이후 n개의 정수 (공백 구분)",
            "2행: 집합 B 원소 수 m, 이후 m개의 정수 (공백 구분)",
            "자료형: int (scanf(\"%d\", &arr[i]))",
        ],
        inputExample: ["4 1 2 3 4", "4 3 4 5 6"],
        outputDesign: [
            "1행: 교집합 원소를 오름차순으로 공백 구분 출력 (공집합이면 0)",
            "2행: 합집합 원소를 오름차순으로 공백 구분 출력",
        ],
        outputExample: ["3 4", "1 2 3 4 5 6"],
        constraints: [
            "버블 정렬로 오름차순 정렬 후 출력",
            "교집합 크기가 0이면 0 출력",
            "합집합은 중복 없이 구성 (B의 원소 중 A에 없는 것만 추가)",
        ],
    },

    s3: {
        programName: "교집합과 합집합 계산기",
        flowchart: [
            "① 시작",
            "② scanf n → a[n] 입력 / scanf m → b[m] 입력",
            "③ 교집합 계산:",
            "   for i in a: if a[i] in b: inter에 추가",
            "④ 합집합 계산:",
            "   inter 복사 → for j in b: if b[j] not in a: uni에 추가",
            "   또는: a 전체 복사 → b 원소 중 a에 없으면 uni에 추가",
            "⑤ 버블 정렬(inter), 버블 정렬(uni)",
            "⑥ if inter_size==0: printf 0 / else: printf inter 원소들",
            "⑦ printf uni 원소들",
            "⑧ 끝",
        ],
        pseudocode: [
            "scanf n; for i=0..n-1: scanf a[i]",
            "scanf m; for j=0..m-1: scanf b[j]",
            "",
            "/* 교집합 */",
            "inter_size ← 0",
            "for i=0..n-1:",
            "  for j=0..m-1:",
            "    if a[i]==b[j]: inter[inter_size++] ← a[i]; break",
            "",
            "/* 합집합 = a 전체 + b 원소 중 a에 없는 것 */",
            "uni_size ← n; copy a→uni",
            "for j=0..m-1:",
            "  found ← false",
            "  for i=0..n-1: if a[i]==b[j]: found←true; break",
            "  if not found: uni[uni_size++] ← b[j]",
            "",
            "버블 정렬(inter, inter_size)",
            "버블 정렬(uni, uni_size)",
            "",
            "if inter_size==0: printf 0",
            "else: printf inter 원소들",
            "printf uni 원소들",
        ],
    },

    s4: {
        programName: "교집합과 합집합 계산기",
        code: [
            "#include <stdio.h>",
            "",
            "void bubble_sort(int arr[], int size) {",
            "    for (int i = 0; i < size - 1; i++)",
            "        for (int j = 0; j < size - 1 - i; j++)",
            "            if (arr[j] > arr[j+1]) {",
            "                int tmp = arr[j]; arr[j] = arr[j+1]; arr[j+1] = tmp;",
            "            }",
            "}",
            "",
            "int main() {",
            "    int a[100], b[100], inter[100], uni[100];",
            "    int n, m, inter_size = 0, uni_size = 0;",
            "",
            "    /* 1. 입력 */",
            "    scanf(\"%d\", &n);",
            "    for (int i = 0; i < n; i++) scanf(\"%d\", &a[i]);",
            "    scanf(\"%d\", &m);",
            "    for (int i = 0; i < m; i++) scanf(\"%d\", &b[i]);",
            "",
            "    /* 2. 교집합: a의 원소가 b에도 있으면 추가 */",
            "    for (int i = 0; i < n; i++)",
            "        for (int j = 0; j < m; j++)",
            "            if (a[i] == b[j]) { inter[inter_size++] = a[i]; break; }",
            "",
            "    /* 3. 합집합: a 전체 복사 후, b 원소 중 a에 없는 것 추가 */",
            "    for (int i = 0; i < n; i++) uni[uni_size++] = a[i];",
            "    for (int j = 0; j < m; j++) {",
            "        int found = 0;",
            "        for (int i = 0; i < n; i++)",
            "            if (a[i] == b[j]) { found = 1; break; }",
            "        if (!found) uni[uni_size++] = b[j];",
            "    }",
            "",
            "    /* 4. 오름차순 정렬 */",
            "    bubble_sort(inter, inter_size);",
            "    bubble_sort(uni, uni_size);",
            "",
            "    /* 5. 교집합 출력 (공집합이면 0) */",
            "    if (inter_size == 0) { printf(\"0\\n\"); }",
            "    else {",
            "        for (int i = 0; i < inter_size; i++)",
            "            printf(\"%d%s\", inter[i], i < inter_size-1 ? \" \" : \"\\n\");",
            "    }",
            "",
            "    /* 6. 합집합 출력 */",
            "    for (int i = 0; i < uni_size; i++)",
            "        printf(\"%d%s\", uni[i], i < uni_size-1 ? \" \" : \"\\n\");",
            "",
            "    return 0;",
            "}",
        ],
        explanation: [
            "3~8행: bubble_sort 함수 — 오름차순 버블 정렬",
            "  인접 원소를 비교하여 큰 값을 오른쪽으로 이동",
            "",
            "15~18행: 두 집합의 원소를 각각 배열 a, b에 입력받음",
            "  n: a의 원소 수 / m: b의 원소 수",
            "",
            "21~23행: 교집합 — a[i]와 동일한 값이 b에 있으면 inter에 추가",
            "  내부 루프에서 break로 중복 추가 방지",
            "",
            "26~31행: 합집합 — a 전체를 uni에 복사 후, b 원소 중 a에 없는 것만 추가",
            "  found 플래그로 중복 여부 확인",
            "",
            "37~43행: 교집합·합집합 출력 (마지막 원소 뒤에는 공백 없이 개행)",
        ],
    },

    s5: {
        programName: "교집합과 합집합 계산기",
        errors: [
            "교집합 탐색 시 break 없이 모든 b를 순회하면 a[i]가 b에 여러 번 있을 때 inter에 중복 추가됨. 일치 시 break 필수.",
            "sorted() 없이(버블 정렬 없이) 출력하면 순서가 보장되지 않아 채점 오류 발생.",
        ],
        improvements: [
            "입력 형식을 '원소 수 없이 한 줄에 원소만'으로 받으려면 fgets + sscanf 조합이 필요하다.",
            "원소 범위가 제한적이면 체크 배열(visited[MAX])로 교집합·합집합을 O(n) 시간에 구현할 수 있다.",
        ],
        testCases: [
            {input: "4 1 2 3 4 / 4 3 4 5 6", expected: "3 4 / 1 2 3 4 5 6", actual: "3 4 / 1 2 3 4 5 6", pass: "O"},
            {input: "3 1 2 3 / 3 4 5 6 (공집합)", expected: "0 / 1 2 3 4 5 6", actual: "0 / 1 2 3 4 5 6", pass: "O"},
            {input: "5 1 2 3 4 5 / 2 2 4 (부분집합)", expected: "2 4 / 1 2 3 4 5", actual: "2 4 / 1 2 3 4 5", pass: "O"},
            {input: "교집합 break 누락 시", expected: "중복 없는 교집합", actual: "중복 추가 오류", pass: "X"},
        ],
    },
}, "../c/3-2-14.docx");
