// 원의 겹침 여부 판별하기 (Project 3-2-10) — C 언어 버전
const {makeDocument} = require('./make_sw_template');

makeDocument({
    s1: {
        programName: "원의 겹침 여부 판별하기",
        purpose: [
            "두 원의 중심 좌표(x1,y1), (x2,y2)와 반지름 r1, r2를 입력받아 두 원의 위치 관계(외부 분리·외접·교차·내접·내부 포함)를 판별하고 출력한다.",
        ],
        targetUser: "조건문과 수학 공식을 학습하거나 부동소수점 없이 정수 연산으로 처리하는 방법에 관심 있는 누구나",
        features: [
            "① scanf로 두 원의 정보(x, y, r)를 각각 입력받는다.",
            "② 두 중심 사이의 거리 제곱(d_sq)을 long long으로 계산한다.",
            "③ 반지름 합의 제곱(sum_sq)과 반지름 차의 절댓값 제곱(diff_sq)과 비교한다.",
            "④ 5가지 경우(외부·외접·교차·내접·내부포함)를 정확히 판별하여 출력한다.",
        ],
        screenExample: [
            "(입력)  0 0 3",
            "        6 0 3",
            "(출력)  한 점에서 만난다",
            "",
            "(입력)  0 0 3",
            "        4 0 3",
            "(출력)  두 점에서 만난다",
        ],
    },

    s2: {
        programName: "원의 겹침 여부 판별하기",
        inputDesign: [
            "1행: 정수 x1, y1, r1 (공백 구분) — 첫 번째 원의 중심 좌표와 반지름",
            "2행: 정수 x2, y2, r2 (공백 구분) — 두 번째 원의 중심 좌표와 반지름",
            "자료형: int (scanf(\"%d %d %d\", &x, &y, &r))",
        ],
        inputExample: ["0 0 3", "4 0 3"],
        outputDesign: [
            "조건에 따라 3가지 중 하나를 출력:",
            "  외부 분리(d_sq>sum_sq) 또는 내부 포함(d_sq<diff_sq) → \"만나지 않는다\"",
            "  외접(d_sq==sum_sq) 또는 내접(d_sq==diff_sq) → \"한 점에서 만난다\"",
            "  두 점 교차(diff_sq<d_sq<sum_sq) → \"두 점에서 만난다\"",
        ],
        outputExample: ["두 점에서 만난다"],
        constraints: [
            "sqrt를 쓰지 않고 제곱 비교를 사용하여 부동소수점 오차를 방지",
            "d_sq==(r1+r2)² (외접)와 d_sq==(r1-r2)² (내접) 경계 처리 필수",
            "좌표값이 클 때 오버플로우 방지를 위해 long long 사용",
        ],
    },

    s3: {
        programName: "원의 겹침 여부 판별하기",
        flowchart: [
            "① 시작",
            "② scanf(\"%d %d %d\", &x1, &y1, &r1)",
            "③ scanf(\"%d %d %d\", &x2, &y2, &r2)",
            "④ d_sq ← (x2-x1)² + (y2-y1)²",
            "⑤ sum_sq ← (r1+r2)²",
            "⑥ diff ← abs(r1-r2), diff_sq ← diff²",
            "⑦ if d_sq > sum_sq: printf(\"만나지 않는다\")",
            "   else if d_sq == sum_sq: printf(\"한 점에서 만난다\")",
            "   else if d_sq > diff_sq: printf(\"두 점에서 만난다\")",
            "   else if d_sq == diff_sq: printf(\"한 점에서 만난다\")",
            "   else: printf(\"만나지 않는다\")",
            "⑧ 끝",
        ],
        pseudocode: [
            "scanf(\"%d %d %d\", &x1, &y1, &r1)",
            "scanf(\"%d %d %d\", &x2, &y2, &r2)",
            "",
            "d_sq    ← (x2-x1)*(x2-x1) + (y2-y1)*(y2-y1)",
            "sum_sq  ← (long long)(r1+r2)*(r1+r2)",
            "diff    ← abs(r1-r2)",
            "diff_sq ← (long long)diff*diff",
            "",
            "if d_sq > sum_sq: printf(\"만나지 않는다\")",
            "else if d_sq == sum_sq: printf(\"한 점에서 만난다\")",
            "else if d_sq > diff_sq: printf(\"두 점에서 만난다\")",
            "else if d_sq == diff_sq: printf(\"한 점에서 만난다\")",
            "else: printf(\"만나지 않는다\")",
        ],
    },

    s4: {
        programName: "원의 겹침 여부 판별하기",
        code: [
            "#include <stdio.h>",
            "#include <stdlib.h>  /* abs() */",
            "",
            "int main() {",
            "    int x1, y1, r1, x2, y2, r2;",
            "    scanf(\"%d %d %d\", &x1, &y1, &r1);",
            "    scanf(\"%d %d %d\", &x2, &y2, &r2);",
            "",
            "    /* 제곱 거리 계산 (sqrt 미사용 → 부동소수점 오차 방지) */",
            "    long long d_sq = (long long)(x2-x1)*(x2-x1) + (long long)(y2-y1)*(y2-y1);",
            "",
            "    /* 반지름 합/차의 제곱 */",
            "    long long sum_sq  = (long long)(r1+r2) * (r1+r2);",
            "    int diff = abs(r1 - r2);",
            "    long long diff_sq = (long long)diff * diff;",
            "",
            "    /* 5케이스 완전 판별 */",
            "    if (d_sq > sum_sq)",
            "        printf(\"만나지 않는다\\n\");       /* 케이스 1: 외부 분리 */",
            "    else if (d_sq == sum_sq)",
            "        printf(\"한 점에서 만난다\\n\");    /* 케이스 2: 외접 */",
            "    else if (d_sq > diff_sq)",
            "        printf(\"두 점에서 만난다\\n\");    /* 케이스 3: 두 점 교차 */",
            "    else if (d_sq == diff_sq)",
            "        printf(\"한 점에서 만난다\\n\");    /* 케이스 4: 내접 */",
            "    else",
            "        printf(\"만나지 않는다\\n\");       /* 케이스 5: 내부 포함 */",
            "",
            "    return 0;",
            "}",
        ],
        explanation: [
            "1~2행: stdio.h (입출력), stdlib.h (abs 함수) 헤더 포함",
            "",
            "5~7행: 두 원의 중심 좌표와 반지름을 각각 scanf로 입력받음",
            "",
            "10행: d_sq — 두 중심 사이의 거리 제곱 (long long으로 오버플로우 방지)",
            "",
            "13행: sum_sq — (r1+r2)² : 외접/외부 분리의 경계값",
            "14~15행: diff_sq — (|r1-r2|)² : 내접/내부 포함의 경계값",
            "  abs(r1-r2)로 절댓값 처리 (r1>r2, r1<r2 모두 대응)",
            "",
            "18~27행: d_sq와 경계값을 비교하여 5케이스 판별",
        ],
    },

    s5: {
        programName: "원의 겹침 여부 판별하기",
        errors: [
            "sqrt()를 사용하고 d == r1+r2로 비교하면 부동소수점 오차로 외접·내접 판별이 실패할 수 있다.",
            "5케이스 대신 3케이스만 처리하면 내접(d=|r1-r2|)과 내부 포함(d<|r1-r2|)을 \"두 점에서 만난다\"로 잘못 출력한다.",
            "int 범위를 벗어나는 좌표에서 d_sq 계산 시 long long으로 캐스팅하지 않으면 오버플로우 발생.",
        ],
        improvements: [
            "long long을 사용하면 좌표값이 크더라도 오버플로우 없이 안전하게 계산할 수 있다.",
            "abs()는 <stdlib.h>에 정의되어 있으므로 반드시 헤더를 포함해야 한다.",
        ],
        testCases: [
            {input: "0 0 3 / 10 0 3", expected: "만나지 않는다", actual: "만나지 않는다", pass: "O"},
            {input: "0 0 3 / 6 0 3", expected: "한 점에서 만난다", actual: "한 점에서 만난다", pass: "O"},
            {input: "0 0 3 / 4 0 3", expected: "두 점에서 만난다", actual: "두 점에서 만난다", pass: "O"},
            {input: "0 0 5 / 2 0 3", expected: "한 점에서 만난다", actual: "한 점에서 만난다", pass: "O"},
            {input: "0 0 5 / 1 0 2", expected: "만나지 않는다", actual: "만나지 않는다", pass: "O"},
        ],
    },
}, "../c/3-2-10.docx");
